//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string FOTOGRAF { get; set; }
        public string EGITIM { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string KULLANICI { get; set; }
        public string SIFRE { get; set; }
        public string YETKI { get; set; }
    }
}
